sequenceDiagram
  participant participant_assertFinitePoint as assertFinitePoint
  participant participant_hitTestWorldRects as hitTestWorldRects
  participant_hitTestWorldRects->>participant_assertFinitePoint: assertFinitePoint()
  participant_assertFinitePoint-->>participant_hitTestWorldRects: return
