sequenceDiagram
  participant participant_assertValidViewport as assertValidViewport
  participant participant_constrainAxis as constrainAxis
  participant participant_constrainViewport as constrainViewport
  participant participant_getAlignmentFactor as getAlignmentFactor
  participant participant_panViewport as panViewport
  participant participant_validateConstraints as validateConstraints
  participant_panViewport->>participant_constrainViewport: constrainViewport()
  participant_constrainViewport->>participant_assertValidViewport: assertValidViewport()
  participant_assertValidViewport-->>participant_constrainViewport: return
  participant_constrainViewport->>participant_validateConstraints: validateConstraints()
  participant_validateConstraints-->>participant_constrainViewport: return
  participant_constrainViewport->>participant_constrainAxis: constrainAxis()
  participant_constrainAxis->>participant_getAlignmentFactor: getAlignmentFactor()
  participant_getAlignmentFactor-->>participant_constrainAxis: return
  participant_constrainAxis-->>participant_constrainViewport: return
  participant_constrainViewport-->>participant_panViewport: return
