sequenceDiagram
  participant participant_resolver as resolver
  participant participant_snapWorldCoordinate as snapWorldCoordinate
  participant_snapWorldCoordinate->>participant_resolver: resolver()
  participant_resolver-->>participant_snapWorldCoordinate: return
